collections:
  - name: "repertoire" # Used in routes, e.g., /admin/collections/blog
    label: "Repertoire" # Used in the UI
    folder: "src/content/repertoire" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Aktualisiert am", name: "publishDate", widget: "datetime" }     
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Bild", name: "img", widget: "image" }
      - { label: "Bild Beschreibung", name: "img_alt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "termine" # Used in routes, e.g., /admin/collections/blog
    label: "Termine" # Used in the UI
    folder: "src/content/termine" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Vorstellung", name: "vorstellung", widget: "string" }
      - { label: "Datum", name: "datum", widget: "datetime" }     
      - { label: "Rolle", name: "rolle", widget: "string" }
    extension: json
  - name: "fotos" # Used in routes, e.g., /admin/collections/blog
    label: "Fotos" # Used in the UI
    folder: "src/content/fotos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Hinzugefügt am", name: "publishDate", widget: "datetime" }     
      - { label: "Bild", name: "img", widget: "image" }
      - { label: "Bild Beschreibung", name: "img_alt", widget: "string" }
    extension: json

media_folder: "public/assets" # Location where files will be stored in the repo
public_folder: "public/assets" # The src attribute for uploaded media
locale: 'de'
show_preview_links: false
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)